Product photo
CraftAcademy/jak-sie-masz-slowfood pull request #16
Opened 2018-01-16 14:50 UTC by zuzanna81

## PT Link: https://www.pivotaltracker.com/story/show/154132379

2018-01-16 16:49 UTC, lcegit reviewed
Need to fix asset pipeline or add an image col to the product table.

2018-01-16 16:59 UTC, lcegit commented
@aljoh @oliverochman do you know why our test is failing here?

2018-01-18 15:42 UTC, NegativeKarma reviewed
LGTM

2018-01-19 12:48 UTC, diraulo requested changes
Please fix the indentation in the feature files so we can get a clean code difference to review

2018-01-19 12:48 UTC, diraulo commented on features/restaurant_page.feature
> +    Scenario:
No need to indent the `Scenario` block after the `@googlemap` tag

The following is okay:
```gherkin
@googlemap
Scenario:
  When ...
```

2018-01-19 14:27 UTC, tochman commented
What is the status of this one? Should we review this? Is anybody working on this?

2018-01-19 21:41 UTC, closed without merging