[WIP] Restaurant categories
CraftAcademy/jak-sie-masz-slowfood pull request #9
Opened 2018-01-12 10:47 UTC by lcegit

## PT Link: https://www.pivotaltracker.com/story/show/154205898

2018-01-14 13:43 UTC, lcegit commented
@aljoh @oliverochman Please review ^

2018-01-14 15:40 UTC, aljoh commented on features/restaurant_categories.feature
> +    Then show me the page
Remove "show me the page"

2018-01-14 15:44 UTC, lcegit commented
There's a previous factory for creating restaurant, not sure if this should be included here as well.

2018-01-15 10:28 UTC, lcegit reviewed
The merge conflict was solved manually.

2018-01-15 11:37 UTC, tochman requested changes
Close, but not quite there yet...

2018-01-15 11:37 UTC, tochman commented on app/views/restaurant/index.html.erb
> +    <%= "#{restaurant_category.name}" %>
Why do you string interpolate here?

2018-01-15 11:37 UTC, tochman commented on app/views/restaurant/index.html.erb
> +        <%= link_to 'Show page', restaurant_path(restaurant) %>
Please use other wording, like 'Visit' or make the restaurant name a link.

2018-01-15 13:58 UTC, merged